services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:4.1.4-20220427
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm
  app:
    container_name: app
    build: ../
    ports:
      - 8888:8888
    volumes:
      - ../app:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true